modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="lilicans" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Lilicans" #mandatory
#logoFile="examplemod.png" #optional
credits="" #optional
authors="Kay9" #optional
description='''
Lively lily pads!

For you, my Rae of Sunshine.
'''
[[dependencies.lilicans]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.lilicans]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18, 1.19)"
    ordering="NONE"
    side="BOTH"